// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using project_comp1640_be.Data;

#nullable disable

namespace projectcomp1640be.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240301022718_update-database")]
    partial class updatedatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("project_comp1640_be.Model.Academic_Years", b =>
                {
                    b.Property<int>("academic_year_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("academic_year_id"));

                    b.Property<DateTime?>("academic_Year_endClosureDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("academic_Year_startClosureDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("academic_year_title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("academic_year_id");

                    b.ToTable("Academic_Years");
                });

            modelBuilder.Entity("project_comp1640_be.Model.Contributions", b =>
                {
                    b.Property<int>("contribution_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("contribution_id"));

                    b.Property<int>("IsEnabled")
                        .HasColumnType("int");

                    b.Property<int>("IsSelected")
                        .HasColumnType("int");

                    b.Property<int>("IsView")
                        .HasColumnType("int");

                    b.Property<int?>("academic_yearsacademic_year_id")
                        .HasColumnType("int");

                    b.Property<string>("contribution_content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("contribution_image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("contribution_submition_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("contribution_title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("facultiesfaculty_id")
                        .HasColumnType("int");

                    b.Property<int?>("usersuser_id")
                        .HasColumnType("int");

                    b.HasKey("contribution_id");

                    b.HasIndex("academic_yearsacademic_year_id");

                    b.HasIndex("facultiesfaculty_id");

                    b.HasIndex("usersuser_id");

                    b.ToTable("Contributions");
                });

            modelBuilder.Entity("project_comp1640_be.Model.Faculties", b =>
                {
                    b.Property<int>("faculty_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("faculty_id"));

                    b.Property<string>("faculty_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("faculty_id");

                    b.ToTable("Faculties");
                });

            modelBuilder.Entity("project_comp1640_be.Model.Marketing_Comments", b =>
                {
                    b.Property<int>("comment_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("comment_id"));

                    b.Property<string>("comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("comment_date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("contributionscontribution_id")
                        .HasColumnType("int");

                    b.Property<int?>("usersuser_id")
                        .HasColumnType("int");

                    b.HasKey("comment_id");

                    b.HasIndex("contributionscontribution_id");

                    b.HasIndex("usersuser_id");

                    b.ToTable("Marketing_Comments");
                });

            modelBuilder.Entity("project_comp1640_be.Model.Roles", b =>
                {
                    b.Property<int>("role_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("role_id"));

                    b.Property<string>("role_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("role_id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("project_comp1640_be.Model.Users", b =>
                {
                    b.Property<int>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("user_id"));

                    b.Property<int>("account_status")
                        .HasColumnType("int");

                    b.Property<int>("facultiesfaculty_id")
                        .HasColumnType("int");

                    b.Property<string>("refesh_token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("refesh_token_exprytime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("reset_password_exprytime")
                        .HasColumnType("datetime2");

                    b.Property<string>("reset_password_token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("role_id")
                        .HasColumnType("int");

                    b.Property<string>("token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_confirm_password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("user_password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("user_id");

                    b.HasIndex("facultiesfaculty_id");

                    b.HasIndex("role_id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("project_comp1640_be.Model.Contributions", b =>
                {
                    b.HasOne("project_comp1640_be.Model.Academic_Years", "academic_years")
                        .WithMany("contributions")
                        .HasForeignKey("academic_yearsacademic_year_id");

                    b.HasOne("project_comp1640_be.Model.Faculties", "faculties")
                        .WithMany("contributions")
                        .HasForeignKey("facultiesfaculty_id");

                    b.HasOne("project_comp1640_be.Model.Users", "users")
                        .WithMany("Contributions")
                        .HasForeignKey("usersuser_id");

                    b.Navigation("academic_years");

                    b.Navigation("faculties");

                    b.Navigation("users");
                });

            modelBuilder.Entity("project_comp1640_be.Model.Marketing_Comments", b =>
                {
                    b.HasOne("project_comp1640_be.Model.Contributions", "contributions")
                        .WithMany("Marketing_Comments")
                        .HasForeignKey("contributionscontribution_id");

                    b.HasOne("project_comp1640_be.Model.Users", "users")
                        .WithMany("Marketing_Comments")
                        .HasForeignKey("usersuser_id");

                    b.Navigation("contributions");

                    b.Navigation("users");
                });

            modelBuilder.Entity("project_comp1640_be.Model.Users", b =>
                {
                    b.HasOne("project_comp1640_be.Model.Faculties", "faculties")
                        .WithMany("users")
                        .HasForeignKey("facultiesfaculty_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("project_comp1640_be.Model.Roles", "role")
                        .WithMany("users")
                        .HasForeignKey("role_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("faculties");

                    b.Navigation("role");
                });

            modelBuilder.Entity("project_comp1640_be.Model.Academic_Years", b =>
                {
                    b.Navigation("contributions");
                });

            modelBuilder.Entity("project_comp1640_be.Model.Contributions", b =>
                {
                    b.Navigation("Marketing_Comments");
                });

            modelBuilder.Entity("project_comp1640_be.Model.Faculties", b =>
                {
                    b.Navigation("contributions");

                    b.Navigation("users");
                });

            modelBuilder.Entity("project_comp1640_be.Model.Roles", b =>
                {
                    b.Navigation("users");
                });

            modelBuilder.Entity("project_comp1640_be.Model.Users", b =>
                {
                    b.Navigation("Contributions");

                    b.Navigation("Marketing_Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
